config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'tweets#index'

  resources :tweets do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :tweet
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :tweet


    
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :favorites
    has_many :comments


    
    # @tweet.favoritesの中に、引数で送られたuserのidがあるかどうか？
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = current_user.comments.build(comment_params)
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet.id)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to tweet_path
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # def create
  #   favorite = current_user.favorites.build(tweet_id: params[:id])
  #   favorite.save
  #   redirect_to tweets_path
  # end

  # def destroy
  #   favorite = Favorite.find(tweet_id: params[:tweet_id], user_id: current_user.id)
  #   favorite.destroy
  #   redirect_to tweets_path
  # end
  def create
    # こう記述することで、「current_userに関連したFavoriteクラスの新しいインスタンス」が作成可能。
    # つまり、favorite.user_id = current_user.idが済んだ状態で生成されている。
    # buildはnewと同じ意味で、アソシエーションしながらインスタンスをnewする時に形式的に使われる。
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweets_path
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, except: [:index]  # deviseのメソッドで「ログインしていないユーザーをログイン画面に送る」メソッド
    
    def index
        @tweets = Tweet.all 
    end

    def new
        # 新規投稿用レイアウト作成
        @tweet = Tweet.new 
    end

    def create
        @tweet = Tweet.new(tweet_params)  # フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
        @tweet.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
        @tweet.save
        redirect_to tweets_path
    end

    def show
        @tweet = Tweet.find(params[:id])
        @user = @tweet.user
        @favorites = @tweet.favorites
        @comment = current_user.comments.build
        @comments = @tweet.comments
    end

    private
    def tweet_params
      params.require(:tweet).permit(:body) # tweetモデルのbodyカラムのみを許可
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @tweets = @user.tweets
        @favorite_tweets = @user.favorite_tweets
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>  <!-- deviseのメソッドで、「ログインしているかしていないかでtrue or falseを返す」メソッド -->
    <%# ログインしていれば %>
      <%= link_to "新規投稿", new_tweet_path %>
      <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
      <%= link_to "マイページ", user_path(current_user.id) %>
    <% else %>
    <%# ログインしていなければ %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>


      <%= link_to "ツイート一覧", tweets_path %>
      <%= link_to "ユーザー一覧", users_path %>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>


<% @tweets.each do |tweet| %>
  <hr>
  <p><span>ツイート内容: </span><%=link_to tweet.body, tweet_path(tweet.id) %></p>
  <%# もしユーザーがログインしていたらtrue %>
  <% if user_signed_in? %>
  <%# ログインしていれば %>
    <% if tweet.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><span>お気に入り解除: </span><%= link_to tweet.favorites.count, tweet_favorites_path(tweet.id), data: { turbo_method: :delete } %></p>
    <% else %>
        <p><span>お気に入り登録: </span><%= link_to tweet.favorites.count, tweet_favorites_path(tweet.id), data: { turbo_method: :post } %></p>
    <% end %>
  <% else %>
  <%# ログインしていなければ %>
    <p><span>お気に入り数: </span><%= tweet.favorites.count %></p>
  <% end %>

<% end %>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>


<%= form_with model: @tweet do |f| %>
  <p>
    <%= f.label :body,"ツイート" %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>

<p>ツイート内容：<%=  @tweet.body %></p>

<p>user:<%=  @user.email %></p>

<p>お気に入り数<%= @favorites.count %></p>

<%= form_with model:[@tweet, @comment] do |f| %>
  <p>
    <%= f.label :body,"コメント" %>
    <%= f.text_field :body %>
  </p>
   <%= f.submit %>
<% end %>


<% @comments.each do |comment| %>
<%# email %>
<p><%= comment.user.email %></p>
<%# comment %>
<p><%= comment.body %></p>

<%= button_to "削除", tweet_comment_path(@tweet, comment), method: :delete %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user|%>

<p>email:<%= link_to user.email, user_path(user.id)%><p>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>

<p><span>email: </span><%= @user.email %></p>

<% @tweets.each do |tweet|%>
<p><span>tweets: </span><%= link_to tweet.body,tweet_path(tweet.id) %></p>
<% end %>

<% @favorite_tweets.each do |tweet| %>
  <hr>
  <p><span>ファボツイート内容: </span><%=link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>